### PR TITLE
Adds NLI policy and fixes IFI typo

### PR DESCRIPTION
**Pull request by kieranjol**
Adds NLI and fixes typo in IFI. This corrects the failed PRs #2 and #4

### CODE REVIEW

**Comment by kieranjol** [comment]
Im not that familiar with github actions - looks like the csv to markdown job has skipped? Or does it kick in after merging?

**Review by ross-spencer — APPROVED** [review]
LGTM!

**Comment by ross-spencer** [comment]
>  Or does it kick in after merging?

Indeed, it's when a push to `main` happens:

* https://github.com/digipres/policies/blob/6348c59d025b7d913eb10ecd87f7e2060b910744/.github/workflows/convert_to_md.yml#L5-L10

We should consider adding a validation setup for the PR and possibly have the PR write the README at the same time so that can be QA'd. 

Let's see if this merge does the trick this time though!

**Comment by ross-spencer** [comment]
Looks like it worked! https://github.com/digipres/policies/commit/bec490f4355dd50d2c70711484518e6f9a207330

**Comment by kieranjol** [comment]
It worked!! Agreed on the action kicking in before merging for QA purposes but I’ve no idea how much work that is. Thanks for all your work on sorting through my PRs!

**Pull request merged**
