### PR TITLE
Remove typos in Irish sections

### PR DESCRIPTION
**Pull request by kieranjol**
Just noticed some typos and capitalisation issues with the Irish instances. I didn't add this to the version history as it was such a minor change.
I've also noticed a pre-existing issue regarding special characters breaking links in the ToC, but I'll make an issue for that.

### CODE REVIEW

**Comment by kieranjol** [comment]
it looks like this commit was reversed by @caylinssmith in https://github.com/digipres/policies/commit/707318d63f9ce0f9937648ae7bc5a0cefd028676 ?Perhaps this happened automatically due to github workflows failing some checks?

**Comment by ross-spencer** [comment]
@anjackson @caylinssmith the repo probably needs branch protection, there are some basic rules there like requiring a pull request and one approval before merging. I haven't the powers to do that on this repo, but maybe you can take a look?

**Comment by anjackson** [comment]
@ross-spencer I've made you and @caylinssmith admins, but I think things are actually working correctly, but are confusing.

I should not have accepted @kieranjol changes because they were made against the Markdown rather than the source CSV. The whole point of the GitHub Action is to generate the `README.md` from the CSV, so the GitHub Action that follows the commit just overwrites any changes to the Markdown.

**Comment by kieranjol** [comment]
I've updated CSV here, hopefully this works! https://github.com/digipres/policies/pull/6

**Pull request merged**
