### PR TITLE
Added KB Netherlands policy

### PR DESCRIPTION
**Pull request by bitsgalore**

### CODE REVIEW

**Comment by kieranjol** [comment]
Hi Johan, unless the GitHub action has changed, I believe that all edits have to happen on the csv, which then updates the markdown. If the PR is merged, it gets automatically reverted. 

See https://github.com/digipres/policies/pull/2#issuecomment-1791662732

**Comment by bitsgalore** [comment]
@kieranjol Thanks for pointing this out, perhaps this could be made more clear in a section on contribution guidelines? Right now this isn't obvious at all (although I did wonder why the same info was repeated in 2 separate docs!).

This also means that the broken links issue should be addressed in the Github Actions script that generates the readme.

(BTW  the CSV isn't particularly easy to edit either, but that's another story).

**Comment by ross-spencer** [comment]
From what I can see, this PR needs reworking to maintain this commit:

https://github.com/digipres/policies/pull/8/commits/a7d9bbd16c21ec0c14d5d40f8b7e493a9b27dc09

So dropping the other two commits, and then making link corrections in the CSV as well, probably under a different commit. But there shouldn't be a markdown change in these commits at all. You will need to force push once the changes to your development branch once you've made the changes.

> (BTW the CSV isn't particularly easy to edit either, but that's another story).

Is there a constructive way to make that comment or surface that discussion?

**Comment by bitsgalore** [comment]
@ross-spencer Hang on, I'll create a new PR, probably easier than modifying this one!

**Pull request closed without merging**
